### ISSUE TITLE
README mistake.

### ISSUE THREAD

**Issue by hechien** [peter-murach/loaf#4]
`braedcrumb "#{@category.title}", blog_category_path(@category)`

I think it might be: `breadcrumb "#{@category.title}", blog_category_path(@category)`

**Comment by neilsmith** [comment]
Spotted other one - if I understand correctly,

````
breadcrumb "#{@category.title}, [:blog, @category]"
````

should perhaps be:

````
breadcrumb "#{@category.title}", [:blog, @category]
````

**Comment by peter-murach** [comment]
Fixed by @igas and @bigardone
