### ISSUE TITLE
Proc was removed?

### ISSUE THREAD

**Issue by philipgiuliani** [peter-murach/loaf#7]
Since this method isn't used anymore, procs are not working:
https://github.com/peter-murach/loaf/blob/master/lib/loaf/controller_extensions.rb#L28

The I18n Scope is also not configurable in the current version.

**Comment by peter-murach** [comment]
Hi Philip, thanks for reporting this. On the issue of procs, in my recent work I didn't have requirement to use procs and thus deemed it unnecessary for the release. However, if you could provide a use case or failing test I would be happy to look into it. It terms of translations, would you have time to investigate? There is already a test app to help you out testing this feature.

**Comment by peter-murach** [comment]
@philipgiuliani Please see readme for details, both scope and procs should work. Please get `0.5.0` version if you still need this functionality.

**Comment by philipgiuliani** [comment]
Oh sorry i forgot to answer you. I need it for `Model.model_name.human`  for example. So i dont have to duplicate the model names in the translations.

Thanks i will start with the implementation on sunday.
